In [54]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle
import pandas as pd
import numpy as np

In [55]:
model = load_model('model.h5')

with open('onehot_geo.pkl','rb') as file :
    onehot_geo = pickle.load(file)

with open('label_encoder_gender.pkl','rb') as file :
    label_encoder_gender = pickle.load(file)

with open('scaler.pkl','rb') as file :
    scaler = pickle.load(file)

In [51]:
label_encoder_gender.transform(['Male'])

array([1])

In [56]:
data = {
    'CreditScore' : 600,
    'Geography' : 'France',
    'Gender' : 'Male',
    'Age' : 40,
    'Tenure' : 3,
    'Balance' : 60000,
    'NumOfProducts' : 2,
    'HasCrCard' : 1,
    'IsActiveMember' : 1,
    'EstimatedSalary' : 50000
}
data = pd.DataFrame([data])
data

CreditScore Geography Gender  Age  Tenure  Balance  NumOfProducts  \
0          600    France   Male   40       3    60000              2   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1            50000

In [57]:
geo = onehot_geo.transform(data[['Geography']]).toarray()

In [58]:
geo_df = pd.DataFrame(geo, columns = onehot_geo.get_feature_names_out())

In [59]:
geo_df

Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [60]:
data['Gender'] = label_encoder_gender.transform(data['Gender'])

In [61]:
data = pd.concat([data, geo_df], axis = 1)

In [62]:
data = data.drop('Geography', axis = 1)

In [63]:
data = scaler.transform(data)

In [64]:
data

array([[-0.52111599,  0.91601335,  0.10961719, -0.68538967, -0.2569057 ,
         0.8095029 ,  0.64259497,  0.9687384 , -0.87203322,  0.98560362,
        -0.5698444 , -0.57369368]])

In [65]:
pred = model.predict(data)
pred

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step


array([[0.20247024]], dtype=float32)

In [66]:
prob = pred[0][0]
prob

np.float32(0.20247024)

In [67]:
prob

np.float32(0.20247024)

In [47]:
if prob > 0.5 :
    print('Customer will leave the bank')
else :
    print('Customer will stay in the bank')

Customer will stay in the bank
